# Board definition for QEMU virt aarch64 platform
# Used for parsing ramdumps generated by QEMU's dump-guest-memory

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from boards import Board

# QEMU virt aarch64 platform (4x Cortex-A76)
# Memory: 1GB @ 0x40000000-0x80000000
# Boot args: nokaslr, VA_BITS=39, PAGE_SHIFT=16 (64KB pages)
class QEMU_VIRT(Board):
    def __init__(self):
        Board.__init__(self)
        self.socid = 9999
        self.board_num = "QEMU_VIRT"
        self.cpu = 'cortex-a76'
        self.ram_start = 0x40000000
        self.phys_offset = 0x40000000
        self.imem_start = 0
        self.smem_addr = 0
        self.wdog_addr = None
        self.imem_file_name = None
        self.smem_addr_buildinfo = 0

QEMU_VIRT()
